//
//  CountriesListPresenter.swift
//  Muchaidze_Lecture_28
//
//  Created by Misha Muchaidze on 20220831...
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CountriesListPresentationLogic
{
  func presentSomething(response: CountriesList.Something.Response)
}

class CountriesListPresenter: CountriesListPresentationLogic
{
  weak var viewController: CountriesListDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: CountriesList.Something.Response)
  {
    let viewModel = CountriesList.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
